# Generated by Django 5.1.3 on 2024-11-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGasco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='descripcion_categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_categoria',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='descripcion_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombre_producto',
        ),
    ]
