# Generated by Django 5.1.3 on 2024-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGasco', '0003_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(max_length=500),
        ),
    ]
